fix: prod. Dockerfile

diff --git a/docker/production/Dockerfile b/docker/production/Dockerfile
--- a/docker/production/Dockerfile
+++ b/docker/production/Dockerfile
@@ -9,13 +9,13 @@ WORKDIR /app
 
 # Install dependencies based on the preferred package manager
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
-RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
-
+#RUN \
+#  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+#  elif [ -f package-lock.json ]; then npm ci; \
+#  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+#  else echo "Lockfile not found." && exit 1; \
+#  fi
+RUN yarn
 
 # 2. Rebuild the source code only when needed
 FROM base AS builder
